### ISSUE TITLE
Messed up layout for Mini model.

### ISSUE THREAD

**Issue by ExileFox** [iUltimateLP/launchpad-led-editor#1]
Looks like a random scattering

8x8 grid did fully lit up tho when i tried to do so

**Comment by iUltimateLP** [comment]
I will fix that, could you be my testing person then, because I have no Mini..

**Comment by iUltimateLP** [comment]
I did not found a MIDI mapping for the MIDI, but I think its the same as the S, I tried to fix it, check out the latest release.

**Comment by ExileFox** [comment]
Recompiled the latest version, it still complains about my device does not seem to be a launchpad

Results for the 8x8 grid:
- Top 2x8 does nothing
- Middle 4x8 fully working but the layout is still wrong
- Bottom 2x8 does nothing
- Round button column: partially lights up correctly, is affected by the broken layout:
- Round Keys: A,G,H unlit, C,E has wrong assignment in the layout, BDF lights up but assignment might still be wrong for these as well.
- Round top row buttons aren't in your application as far as i can see and remains unaffected by this application.

![hmmm](http://i.imgur.com/Hc54oav.jpg)

**Comment by ExileFox** [comment]
Does the S model differ from the Mini tho?. (in terms of communication)

See the "launchpad-programmers-reference" PDF for details:
https://drive.google.com/file/d/0B6GFAyrg1QhyNXBVaTd5WUxNT3M/view?usp=sharing

It might be the case of assuming "X-Y layout" while using the "Drum rack layout" or vice versa

I did not found a own programmers manual for the Mini, maybe you could try out the X-Y- layout with a normal midi sending program, because yeah, I can't test it here :smile:

**Comment by iUltimateLP** [comment]
Hmm the X-Y-layout is strange because the notes are duplicated to the lower half, the drum rack layout is the same as the S which we already tried..

**Comment by ExileFox** [comment]
Also something happened to my reply o.0

Anyway; I'll compare the layouts later and check how they differ.

**Comment by iUltimateLP** [comment]
Really nice, thank you!

**Comment by ExileFox** [comment]
it appears to be very different, i'm pasting the RAW data from MIDI-OX:
(oh and by the way: i get different notes when using traktor, it's really confusing. I hope it's still useful)

The 8 round side buttons (A-H) on the right side:

``` haskell
 TIMESTAMP IN PORT STATUS DATA1 DATA2 CHAN NOTE EVENT               
 00000E6D   6   2     90    08    7F    1  G#-1 Note On               
 00000E6D   6   3     90    08    7F    1  G#-1 Note On               
 00000E6D   6   7     90    08    7F    1  G#-1 Note On               
 00000F0E   6   2     90    08    00    1  G#-1 Note Off              
 00000F0E   6   3     90    08    00    1  G#-1 Note Off              
 00000F0E   6   7     90    08    00    1  G#-1 Note Off              
 00001BC0   6   2     90    18    7F    1  C  1 Note On               
 00001BC0   6   3     90    18    7F    1  C  1 Note On               
 00001BC0   6   7     90    18    7F    1  C  1 Note On               
 00001C43   6   2     90    18    00    1  C  1 Note Off              
 00001C43   6   3     90    18    00    1  C  1 Note Off              
 00001C43   6   7     90    18    00    1  C  1 Note Off              
 00001FCF   6   2     90    28    7F    1  E  2 Note On               
 00001FCF   6   3     90    28    7F    1  E  2 Note On               
 00001FCF   6   7     90    28    7F    1  E  2 Note On               
 00002077   6   2     90    28    00    1  E  2 Note Off              
 00002077   6   3     90    28    00    1  E  2 Note Off              
 00002077   6   7     90    28    00    1  E  2 Note Off              
 000031F5   6   2     90    38    7F    1  G# 3 Note On               
 000031F5   6   3     90    38    7F    1  G# 3 Note On               
 000031F5   6   7     90    38    7F    1  G# 3 Note On               
 000032A3   6   2     90    38    00    1  G# 3 Note Off              
 000032A3   6   3     90    38    00    1  G# 3 Note Off              
 000032A3   6   7     90    38    00    1  G# 3 Note Off              
 00003508   6   2     90    48    7F    1  C  5 Note On               
 00003508   6   3     90    48    7F    1  C  5 Note On               
 00003508   6   7     90    48    7F    1  C  5 Note On               
 00003589   6   2     90    48    00    1  C  5 Note Off              
 00003589   6   3     90    48    00    1  C  5 Note Off              
 00003589   6   7     90    48    00    1  C  5 Note Off              
 0000371E   6   2     90    58    7F    1  E  6 Note On               
 0000371E   6   3     90    58    7F    1  E  6 Note On               
 0000371E   6   7     90    58    7F    1  E  6 Note On               
 000037A7   6   2     90    58    00    1  E  6 Note Off              
 000037A7   6   3     90    58    00    1  E  6 Note Off              
 000037A7   6   7     90    58    00    1  E  6 Note Off              
 0000390F   6   2     90    68    7F    1  G# 7 Note On               
 0000390F   6   3     90    68    7F    1  G# 7 Note On               
 0000390F   6   7     90    68    7F    1  G# 7 Note On               
 0000396B   6   2     90    68    00    1  G# 7 Note Off              
 0000396B   6   3     90    68    00    1  G# 7 Note Off              
 0000396B   6   7     90    68    00    1  G# 7 Note Off              
 00003AD3   6   2     90    78    7F    1  C  9 Note On               
 00003AD3   6   3     90    78    7F    1  C  9 Note On               
 00003AD3   6   7     90    78    7F    1  C  9 Note On               
 00003B1D   6   2     90    78    00    1  C  9 Note Off              
 00003B1D   6   3     90    78    00    1  C  9 Note Off              
 00003B1D   6   7     90    78    00    1  C  9 Note Off              
```

8x8 grid, going from left-to-right, starting from the top:

``` haskell
 TIMESTAMP IN PORT STATUS DATA1 DATA2 CHAN NOTE EVENT               
 000318E2   6   2     90    00    7F    1  C -1 Note On               
 000318E2   6   3     90    00    7F    1  C -1 Note On               
 000318E2   6   7     90    00    7F    1  C -1 Note On               
 000319CB   6   2     90    00    00    1  C -1 Note Off              
 000319CB   6   3     90    00    00    1  C -1 Note Off              
 000319CB   6   7     90    00    00    1  C -1 Note Off              
 000319CE   2   2     90    00    7F    1  C -1 Note On               
 000319CE   2   3     90    00    7F    1  C -1 Note On               
 000319CE   2   7     90    00    7F    1  C -1 Note On               
 00032483   6   2     90    01    7F    1  C#-1 Note On               
 00032483   6   3     90    01    7F    1  C#-1 Note On               
 00032483   6   7     90    01    7F    1  C#-1 Note On               
 00032543   6   2     90    01    00    1  C#-1 Note Off              
 00032543   6   3     90    01    00    1  C#-1 Note Off              
 00032543   6   7     90    01    00    1  C#-1 Note Off              
 00032779   6   2     90    02    7F    1  D -1 Note On               
 00032779   6   3     90    02    7F    1  D -1 Note On               
 00032779   6   7     90    02    7F    1  D -1 Note On               
 000327EF   6   2     90    02    00    1  D -1 Note Off              
 000327EF   6   3     90    02    00    1  D -1 Note Off              
 000327EF   6   7     90    02    00    1  D -1 Note Off              
 00032AE8   6   2     90    03    7F    1  Eb-1 Note On               
 00032AE8   6   3     90    03    7F    1  Eb-1 Note On               
 00032AE8   6   7     90    03    7F    1  Eb-1 Note On               
 00032B69   6   2     90    03    00    1  Eb-1 Note Off              
 00032B69   6   3     90    03    00    1  Eb-1 Note Off              
 00032B69   6   7     90    03    00    1  Eb-1 Note Off              
 00032DEB   6   2     90    04    7F    1  E -1 Note On               
 00032DEB   6   3     90    04    7F    1  E -1 Note On               
 00032DEB   6   7     90    04    7F    1  E -1 Note On               
 00032E25   6   2     90    04    00    1  E -1 Note Off              
 00032E25   6   3     90    04    00    1  E -1 Note Off              
 00032E25   6   7     90    04    00    1  E -1 Note Off              
 00033040   6   2     90    05    7F    1  F -1 Note On               
 00033040   6   3     90    05    7F    1  F -1 Note On               
 00033040   6   7     90    05    7F    1  F -1 Note On               
 0003306F   6   2     90    05    00    1  F -1 Note Off              
 0003306F   6   3     90    05    00    1  F -1 Note Off              
 0003306F   6   7     90    05    00    1  F -1 Note Off              
 00033290   6   2     90    06    7F    1  F#-1 Note On               
 00033290   6   3     90    06    7F    1  F#-1 Note On               
 00033290   6   7     90    06    7F    1  F#-1 Note On               
 000332D4   6   2     90    06    00    1  F#-1 Note Off              
 000332D4   6   3     90    06    00    1  F#-1 Note Off              
 000332D4   6   7     90    06    00    1  F#-1 Note Off              
 000334BB   6   2     90    07    7F    1  G -1 Note On               
 000334BB   6   3     90    07    7F    1  G -1 Note On               
 000334BB   6   7     90    07    7F    1  G -1 Note On               
 000334E7   6   2     90    07    00    1  G -1 Note Off              
 000334E7   6   3     90    07    00    1  G -1 Note Off              
 000334E7   6   7     90    07    00    1  G -1 Note Off              
 00033C18   6   2     90    10    7F    1  E  0 Note On               
 00033C18   6   3     90    10    7F    1  E  0 Note On               
 00033C18   6   7     90    10    7F    1  E  0 Note On               
 00033C5A   6   2     90    10    00    1  E  0 Note Off              
 00033C5A   6   3     90    10    00    1  E  0 Note Off              
 00033C5A   6   7     90    10    00    1  E  0 Note Off              
 00033E31   6   2     90    11    7F    1  F  0 Note On               
 00033E31   6   3     90    11    7F    1  F  0 Note On               
 00033E31   6   7     90    11    7F    1  F  0 Note On               
 00033E46   6   2     90    11    00    1  F  0 Note Off              
 00033E46   6   3     90    11    00    1  F  0 Note Off              
 00033E46   6   7     90    11    00    1  F  0 Note Off              
 0003405C   6   2     90    12    7F    1  F# 0 Note On               
 0003405C   6   3     90    12    7F    1  F# 0 Note On               
 0003405C   6   7     90    12    7F    1  F# 0 Note On               
 00034080   6   2     90    12    00    1  F# 0 Note Off              
 00034080   6   3     90    12    00    1  F# 0 Note Off              
 00034080   6   7     90    12    00    1  F# 0 Note Off              
 0003425D   6   2     90    13    7F    1  G  0 Note On               
 0003425D   6   3     90    13    7F    1  G  0 Note On               
 0003425D   6   7     90    13    7F    1  G  0 Note On               
 00034280   6   2     90    13    00    1  G  0 Note Off              
 00034280   6   3     90    13    00    1  G  0 Note Off              
 00034280   6   7     90    13    00    1  G  0 Note Off              
 00034447   6   2     90    14    7F    1  G# 0 Note On               
 00034447   6   3     90    14    7F    1  G# 0 Note On               
 00034447   6   7     90    14    7F    1  G# 0 Note On               
 00034473   6   2     90    14    00    1  G# 0 Note Off              
 00034473   6   3     90    14    00    1  G# 0 Note Off              
 00034473   6   7     90    14    00    1  G# 0 Note Off              
 00034647   6   2     90    15    7F    1  A  0 Note On               
 00034647   6   3     90    15    7F    1  A  0 Note On               
 00034647   6   7     90    15    7F    1  A  0 Note On               
 0003466F   6   2     90    15    00    1  A  0 Note Off              
 0003466F   6   3     90    15    00    1  A  0 Note Off              
 0003466F   6   7     90    15    00    1  A  0 Note Off              
 00034828   6   2     90    16    7F    1  Bb 0 Note On               
 00034828   6   3     90    16    7F    1  Bb 0 Note On               
 00034828   6   7     90    16    7F    1  Bb 0 Note On               
 0003486A   6   2     90    16    00    1  Bb 0 Note Off              
 0003486A   6   3     90    16    00    1  Bb 0 Note Off              
 0003486A   6   7     90    16    00    1  Bb 0 Note Off              
 000349F9   6   2     90    17    7F    1  B  0 Note On               
 000349F9   6   3     90    17    7F    1  B  0 Note On               
 000349F9   6   7     90    17    7F    1  B  0 Note On               
 00034A1E   6   2     90    17    00    1  B  0 Note Off              
 00034A1E   6   3     90    17    00    1  B  0 Note Off              
 00034A1E   6   7     90    17    00    1  B  0 Note Off              
 00034CF7   6   2     90    20    7F    1  G# 1 Note On               
 00034CF7   6   3     90    20    7F    1  G# 1 Note On               
 00034CF7   6   7     90    20    7F    1  G# 1 Note On               
 00034D21   6   2     90    20    00    1  G# 1 Note Off              
 00034D21   6   3     90    20    00    1  G# 1 Note Off              
 00034D21   6   7     90    20    00    1  G# 1 Note Off              
 00034F05   6   2     90    21    7F    1  A  1 Note On               
 00034F05   6   3     90    21    7F    1  A  1 Note On               
 00034F05   6   7     90    21    7F    1  A  1 Note On               
 00034F47   6   2     90    21    00    1  A  1 Note Off              
 00034F47   6   3     90    21    00    1  A  1 Note Off              
 00034F47   6   7     90    21    00    1  A  1 Note Off              
 000350D3   6   2     90    22    7F    1  Bb 1 Note On               
 000350D3   6   3     90    22    7F    1  Bb 1 Note On               
 000350D3   6   7     90    22    7F    1  Bb 1 Note On               
 00035117   6   2     90    22    00    1  Bb 1 Note Off              
 00035117   6   3     90    22    00    1  Bb 1 Note Off              
 00035117   6   7     90    22    00    1  Bb 1 Note Off              
 000352BD   6   2     90    23    7F    1  B  1 Note On               
 000352BD   6   3     90    23    7F    1  B  1 Note On               
 000352BD   6   7     90    23    7F    1  B  1 Note On               
 000352E1   6   2     90    23    00    1  B  1 Note Off              
 000352E1   6   3     90    23    00    1  B  1 Note Off              
 000352E1   6   7     90    23    00    1  B  1 Note Off              
 00035475   6   2     90    24    7F    1  C  2 Note On               
 00035475   6   3     90    24    7F    1  C  2 Note On               
 00035475   6   7     90    24    7F    1  C  2 Note On               
 0003549B   6   2     90    24    00    1  C  2 Note Off              
 0003549B   6   3     90    24    00    1  C  2 Note Off              
 0003549B   6   7     90    24    00    1  C  2 Note Off              
 00035657   6   2     90    25    7F    1  C# 2 Note On               
 00035657   6   3     90    25    7F    1  C# 2 Note On               
 00035657   6   7     90    25    7F    1  C# 2 Note On               
 00035680   6   2     90    25    00    1  C# 2 Note Off              
 00035680   6   3     90    25    00    1  C# 2 Note Off              
 00035680   6   7     90    25    00    1  C# 2 Note Off              
 0003580B   6   2     90    26    7F    1  D  2 Note On               
 0003580B   6   3     90    26    7F    1  D  2 Note On               
 0003580B   6   7     90    26    7F    1  D  2 Note On               
 0003582B   6   2     90    26    00    1  D  2 Note Off              
 0003582B   6   3     90    26    00    1  D  2 Note Off              
 0003582B   6   7     90    26    00    1  D  2 Note Off              
 000359D0   6   2     90    27    7F    1  Eb 2 Note On               
 000359D0   6   3     90    27    7F    1  Eb 2 Note On               
 000359D0   6   7     90    27    7F    1  Eb 2 Note On               
 000359F8   6   2     90    27    00    1  Eb 2 Note Off              
 000359F8   6   3     90    27    00    1  Eb 2 Note Off              
 000359F8   6   7     90    27    00    1  Eb 2 Note Off              
 00035CB8   6   2     90    30    7F    1  C  3 Note On               
 00035CB8   6   3     90    30    7F    1  C  3 Note On               
 00035CB8   6   7     90    30    7F    1  C  3 Note On               
 00035CEE   6   2     90    30    00    1  C  3 Note Off              
 00035CEE   6   3     90    30    00    1  C  3 Note Off              
 00035CEE   6   7     90    30    00    1  C  3 Note Off              
 00035E6B   6   2     90    31    7F    1  C# 3 Note On               
 00035E6B   6   3     90    31    7F    1  C# 3 Note On               
 00035E6B   6   7     90    31    7F    1  C# 3 Note On               
 00035E94   6   2     90    31    00    1  C# 3 Note Off              
 00035E94   6   3     90    31    00    1  C# 3 Note Off              
 00035E94   6   7     90    31    00    1  C# 3 Note Off              
 0003603F   6   2     90    32    7F    1  D  3 Note On               
 0003603F   6   3     90    32    7F    1  D  3 Note On               
 0003603F   6   7     90    32    7F    1  D  3 Note On               
 00036067   6   2     90    32    00    1  D  3 Note Off              
 00036067   6   3     90    32    00    1  D  3 Note Off              
 00036067   6   7     90    32    00    1  D  3 Note Off              
 0003621A   6   2     90    33    7F    1  Eb 3 Note On               
 0003621A   6   3     90    33    7F    1  Eb 3 Note On               
 0003621A   6   7     90    33    7F    1  Eb 3 Note On               
 00036241   6   2     90    33    00    1  Eb 3 Note Off              
 00036241   6   3     90    33    00    1  Eb 3 Note Off              
 00036241   6   7     90    33    00    1  Eb 3 Note Off              
 00036429   6   2     90    34    7F    1  E  3 Note On               
 00036429   6   3     90    34    7F    1  E  3 Note On               
 00036429   6   7     90    34    7F    1  E  3 Note On               
 0003644D   6   2     90    34    00    1  E  3 Note Off              
 0003644D   6   3     90    34    00    1  E  3 Note Off              
 0003644D   6   7     90    34    00    1  E  3 Note Off              
 00036685   6   2     90    35    7F    1  F  3 Note On               
 00036685   6   3     90    35    7F    1  F  3 Note On               
 00036685   6   7     90    35    7F    1  F  3 Note On               
 000366AB   6   2     90    35    00    1  F  3 Note Off              
 000366AB   6   3     90    35    00    1  F  3 Note Off              
 000366AB   6   7     90    35    00    1  F  3 Note Off              
 00036876   6   2     90    36    7F    1  F# 3 Note On               
 00036876   6   3     90    36    7F    1  F# 3 Note On               
 00036876   6   7     90    36    7F    1  F# 3 Note On               
 000368B7   6   2     90    36    00    1  F# 3 Note Off              
 000368B7   6   3     90    36    00    1  F# 3 Note Off              
 000368B7   6   7     90    36    00    1  F# 3 Note Off              
 00036A46   6   2     90    37    7F    1  G  3 Note On               
 00036A46   6   3     90    37    7F    1  G  3 Note On               
 00036A46   6   7     90    37    7F    1  G  3 Note On               
 00036A6D   6   2     90    37    00    1  G  3 Note Off              
 00036A6D   6   3     90    37    00    1  G  3 Note Off              
 00036A6D   6   7     90    37    00    1  G  3 Note Off              
 00036CE0   6   2     90    40    7F    1  E  4 Note On               
 00036CE0   6   3     90    40    7F    1  E  4 Note On               
 00036CE0   6   7     90    40    7F    1  E  4 Note On               
 00036D13   6   2     90    40    00    1  E  4 Note Off              
 00036D13   6   3     90    40    00    1  E  4 Note Off              
 00036D13   6   7     90    40    00    1  E  4 Note Off              
 00036EE5   6   2     90    41    7F    1  F  4 Note On               
 00036EE5   6   3     90    41    7F    1  F  4 Note On               
 00036EE5   6   7     90    41    7F    1  F  4 Note On               
 00036F13   6   2     90    41    00    1  F  4 Note Off              
 00036F13   6   3     90    41    00    1  F  4 Note Off              
 00036F13   6   7     90    41    00    1  F  4 Note Off              
 000370B0   6   2     90    42    7F    1  F# 4 Note On               
 000370B0   6   3     90    42    7F    1  F# 4 Note On               
 000370B0   6   7     90    42    7F    1  F# 4 Note On               
 000370DC   6   2     90    42    00    1  F# 4 Note Off              
 000370DC   6   3     90    42    00    1  F# 4 Note Off              
 000370DC   6   7     90    42    00    1  F# 4 Note Off              
 00037293   6   2     90    43    7F    1  G  4 Note On               
 00037293   6   3     90    43    7F    1  G  4 Note On               
 00037293   6   7     90    43    7F    1  G  4 Note On               
 000372C1   6   2     90    43    00    1  G  4 Note Off              
 000372C1   6   3     90    43    00    1  G  4 Note Off              
 000372C1   6   7     90    43    00    1  G  4 Note Off              
 00037482   6   2     90    44    7F    1  G# 4 Note On               
 00037482   6   3     90    44    7F    1  G# 4 Note On               
 00037482   6   7     90    44    7F    1  G# 4 Note On               
 000374AD   6   2     90    44    00    1  G# 4 Note Off              
 000374AD   6   3     90    44    00    1  G# 4 Note Off              
 000374AD   6   7     90    44    00    1  G# 4 Note Off              
 0003766B   6   2     90    45    7F    1  A  4 Note On               
 0003766B   6   3     90    45    7F    1  A  4 Note On               
 0003766B   6   7     90    45    7F    1  A  4 Note On               
 00037696   6   2     90    45    00    1  A  4 Note Off              
 00037696   6   3     90    45    00    1  A  4 Note Off              
 00037696   6   7     90    45    00    1  A  4 Note Off              
 0003781E   6   2     90    46    7F    1  Bb 4 Note On               
 0003781E   6   3     90    46    7F    1  Bb 4 Note On               
 0003781E   6   7     90    46    7F    1  Bb 4 Note On               
 0003784C   6   2     90    46    00    1  Bb 4 Note Off              
 0003784C   6   3     90    46    00    1  Bb 4 Note Off              
 0003784C   6   7     90    46    00    1  Bb 4 Note Off              
 000379CD   6   2     90    47    7F    1  B  4 Note On               
 000379CD   6   3     90    47    7F    1  B  4 Note On               
 000379CD   6   7     90    47    7F    1  B  4 Note On               
 000379F5   6   2     90    47    00    1  B  4 Note Off              
 000379F5   6   3     90    47    00    1  B  4 Note Off              
 000379F5   6   7     90    47    00    1  B  4 Note Off              
 00037CB7   6   2     90    50    7F    1  G# 5 Note On               
 00037CB7   6   3     90    50    7F    1  G# 5 Note On               
 00037CB7   6   7     90    50    7F    1  G# 5 Note On               
 00037CE8   6   2     90    50    00    1  G# 5 Note Off              
 00037CE8   6   3     90    50    00    1  G# 5 Note Off              
 00037CE8   6   7     90    50    00    1  G# 5 Note Off              
 00037E92   6   2     90    51    7F    1  A  5 Note On               
 00037E92   6   3     90    51    7F    1  A  5 Note On               
 00037E92   6   7     90    51    7F    1  A  5 Note On               
 00037EBF   6   2     90    51    00    1  A  5 Note Off              
 00037EBF   6   3     90    51    00    1  A  5 Note Off              
 00037EBF   6   7     90    51    00    1  A  5 Note Off              
 00038D53   6   2     90    52    7F    1  Bb 5 Note On               
 00038D53   6   3     90    52    7F    1  Bb 5 Note On               
 00038D53   6   7     90    52    7F    1  Bb 5 Note On               
 00038DE9   6   2     90    52    00    1  Bb 5 Note Off              
 00038DE9   6   3     90    52    00    1  Bb 5 Note Off              
 00038DE9   6   7     90    52    00    1  Bb 5 Note Off              
 0003A747   6   2     90    53    7F    1  B  5 Note On               
 0003A747   6   3     90    53    7F    1  B  5 Note On               
 0003A747   6   7     90    53    7F    1  B  5 Note On               
 0003A786   6   2     90    53    00    1  B  5 Note Off              
 0003A786   6   3     90    53    00    1  B  5 Note Off              
 0003A786   6   7     90    53    00    1  B  5 Note Off              
 0003AFF6   6   2     90    54    7F    1  C  6 Note On               
 0003AFF6   6   3     90    54    7F    1  C  6 Note On               
 0003AFF6   6   7     90    54    7F    1  C  6 Note On               
 0003B0B1   6   2     90    54    00    1  C  6 Note Off              
 0003B0B1   6   3     90    54    00    1  C  6 Note Off              
 0003B0B1   6   7     90    54    00    1  C  6 Note Off              
 0003B313   6   2     90    55    7F    1  C# 6 Note On               
 0003B313   6   3     90    55    7F    1  C# 6 Note On               
 0003B313   6   7     90    55    7F    1  C# 6 Note On               
 0003B3DF   6   2     90    55    00    1  C# 6 Note Off              
 0003B3DF   6   3     90    55    00    1  C# 6 Note Off              
 0003B3DF   6   7     90    55    00    1  C# 6 Note Off              
 0003B594   6   2     90    56    7F    1  D  6 Note On               
 0003B594   6   3     90    56    7F    1  D  6 Note On               
 0003B594   6   7     90    56    7F    1  D  6 Note On               
 0003B67D   6   2     90    56    00    1  D  6 Note Off              
 0003B67D   6   3     90    56    00    1  D  6 Note Off              
 0003B67D   6   7     90    56    00    1  D  6 Note Off              
 0003B812   6   2     90    57    7F    1  Eb 6 Note On               
 0003B812   6   3     90    57    7F    1  Eb 6 Note On               
 0003B812   6   7     90    57    7F    1  Eb 6 Note On               
 0003B8D4   6   2     90    57    00    1  Eb 6 Note Off              
 0003B8D4   6   3     90    57    00    1  Eb 6 Note Off              
 0003B8D4   6   7     90    57    00    1  Eb 6 Note Off              
 0003BC39   6   2     90    60    7F    1  C  7 Note On               
 0003BC39   6   3     90    60    7F    1  C  7 Note On               
 0003BC39   6   7     90    60    7F    1  C  7 Note On               
 0003BC8A   6   2     90    60    00    1  C  7 Note Off              
 0003BC8A   6   3     90    60    00    1  C  7 Note Off              
 0003BC8A   6   7     90    60    00    1  C  7 Note Off              
 0003BEAE   6   2     90    61    7F    1  C# 7 Note On               
 0003BEAE   6   3     90    61    7F    1  C# 7 Note On               
 0003BEAE   6   7     90    61    7F    1  C# 7 Note On               
 0003BEE2   6   2     90    61    00    1  C# 7 Note Off              
 0003BEE2   6   3     90    61    00    1  C# 7 Note Off              
 0003BEE2   6   7     90    61    00    1  C# 7 Note Off              
 0003C0DC   6   2     90    62    7F    1  D  7 Note On               
 0003C0DC   6   3     90    62    7F    1  D  7 Note On               
 0003C0DC   6   7     90    62    7F    1  D  7 Note On               
 0003C112   6   2     90    62    00    1  D  7 Note Off              
 0003C112   6   3     90    62    00    1  D  7 Note Off              
 0003C112   6   7     90    62    00    1  D  7 Note Off              
 0003C31F   6   2     90    63    7F    1  Eb 7 Note On               
 0003C31F   6   3     90    63    7F    1  Eb 7 Note On               
 0003C31F   6   7     90    63    7F    1  Eb 7 Note On               
 0003C33C   6   2     90    63    00    1  Eb 7 Note Off              
 0003C33C   6   3     90    63    00    1  Eb 7 Note Off              
 0003C33C   6   7     90    63    00    1  Eb 7 Note Off              
 0003C52E   6   2     90    64    7F    1  E  7 Note On               
 0003C52E   6   3     90    64    7F    1  E  7 Note On               
 0003C52E   6   7     90    64    7F    1  E  7 Note On               
 0003C55A   6   2     90    64    00    1  E  7 Note Off              
 0003C55A   6   3     90    64    00    1  E  7 Note Off              
 0003C55A   6   7     90    64    00    1  E  7 Note Off              
 0003C76F   6   2     90    65    7F    1  F  7 Note On               
 0003C76F   6   3     90    65    7F    1  F  7 Note On               
 0003C76F   6   7     90    65    7F    1  F  7 Note On               
 0003C79D   6   2     90    65    00    1  F  7 Note Off              
 0003C79D   6   3     90    65    00    1  F  7 Note Off              
 0003C79D   6   7     90    65    00    1  F  7 Note Off              
 0003C990   6   2     90    66    7F    1  F# 7 Note On               
 0003C990   6   3     90    66    7F    1  F# 7 Note On               
 0003C990   6   7     90    66    7F    1  F# 7 Note On               
 0003C9B5   6   2     90    66    00    1  F# 7 Note Off              
 0003C9B5   6   3     90    66    00    1  F# 7 Note Off              
 0003C9B5   6   7     90    66    00    1  F# 7 Note Off              
 0003CBA1   6   2     90    67    7F    1  G  7 Note On               
 0003CBA1   6   3     90    67    7F    1  G  7 Note On               
 0003CBA1   6   7     90    67    7F    1  G  7 Note On               
 0003CBCD   6   2     90    67    00    1  G  7 Note Off              
 0003CBCD   6   3     90    67    00    1  G  7 Note Off              
 0003CBCD   6   7     90    67    00    1  G  7 Note Off              
 0003CE8E   6   2     90    70    7F    1  E  8 Note On               
 0003CE8E   6   3     90    70    7F    1  E  8 Note On               
 0003CE8E   6   7     90    70    7F    1  E  8 Note On               
 0003CEB0   6   2     90    70    00    1  E  8 Note Off              
 0003CEB0   6   3     90    70    00    1  E  8 Note Off              
 0003CEB0   6   7     90    70    00    1  E  8 Note Off              
 0003D0BC   6   2     90    71    7F    1  F  8 Note On               
 0003D0BC   6   3     90    71    7F    1  F  8 Note On               
 0003D0BC   6   7     90    71    7F    1  F  8 Note On               
 0003D0F1   6   2     90    71    00    1  F  8 Note Off              
 0003D0F1   6   3     90    71    00    1  F  8 Note Off              
 0003D0F1   6   7     90    71    00    1  F  8 Note Off              
 0003D2A4   6   2     90    72    7F    1  F# 8 Note On               
 0003D2A4   6   3     90    72    7F    1  F# 8 Note On               
 0003D2A4   6   7     90    72    7F    1  F# 8 Note On               
 0003D2E2   6   2     90    72    00    1  F# 8 Note Off              
 0003D2E2   6   3     90    72    00    1  F# 8 Note Off              
 0003D2E2   6   7     90    72    00    1  F# 8 Note Off              
 0003D490   6   2     90    73    7F    1  G  8 Note On               
 0003D490   6   3     90    73    7F    1  G  8 Note On               
 0003D490   6   7     90    73    7F    1  G  8 Note On               
 0003D4C5   6   2     90    73    00    1  G  8 Note Off              
 0003D4C5   6   3     90    73    00    1  G  8 Note Off              
 0003D4C5   6   7     90    73    00    1  G  8 Note Off              
 0003D67A   6   2     90    74    7F    1  G# 8 Note On               
 0003D67A   6   3     90    74    7F    1  G# 8 Note On               
 0003D67A   6   7     90    74    7F    1  G# 8 Note On               
 0003D6A1   6   2     90    74    00    1  G# 8 Note Off              
 0003D6A1   6   3     90    74    00    1  G# 8 Note Off              
 0003D6A1   6   7     90    74    00    1  G# 8 Note Off              
 0003D862   6   2     90    75    7F    1  A  8 Note On               
 0003D862   6   3     90    75    7F    1  A  8 Note On               
 0003D862   6   7     90    75    7F    1  A  8 Note On               
 0003D897   6   2     90    75    00    1  A  8 Note Off              
 0003D897   6   3     90    75    00    1  A  8 Note Off              
 0003D897   6   7     90    75    00    1  A  8 Note Off              
 0003DA63   6   2     90    76    7F    1  Bb 8 Note On               
 0003DA63   6   3     90    76    7F    1  Bb 8 Note On               
 0003DA63   6   7     90    76    7F    1  Bb 8 Note On               
 0003DA88   6   2     90    76    00    1  Bb 8 Note Off              
 0003DA88   6   3     90    76    00    1  Bb 8 Note Off              
 0003DA88   6   7     90    76    00    1  Bb 8 Note Off              
 0003DC38   6   2     90    77    7F    1  B  8 Note On               
 0003DC38   6   3     90    77    7F    1  B  8 Note On               
 0003DC38   6   7     90    77    7F    1  B  8 Note On               
 0003DC6A   6   2     90    77    00    1  B  8 Note Off              
 0003DC6A   6   3     90    77    00    1  B  8 Note Off              
 0003DC6A   6   7     90    77    00    1  B  8 Note Off              

```

**Comment by iUltimateLP** [comment]
Thank you, with that, I should be able to create a working one! :+1:

**Comment by ExileFox** [comment]
Sounds good :)

**Comment by iUltimateLP** [comment]
Made the main buttons, hope they work, but the side buttons dont work atm, will fix them asap. Fixed in commit https://github.com/iUltimateLP/launchpad-led-editor/commit/35d08e9a52df1a652e2e28a5696dd7f5079c5d41

**Comment by ExileFox** [comment]
8x8 grid works, however the pure green is much more amber than it was previously, it's hard to get it on camera too.
![img_20151206_164752](https://cloud.githubusercontent.com/assets/2000703/11614207/63fde9e6-9c3b-11e5-9b3c-6deeee318f7d.jpg)

Also: i'm still getting that warning message "does not seem to be a launchpad".

**Comment by ByteBitter** [comment]
I have the same problem with my Launchpad S and Launchpad MK1
![img_0166](https://cloud.githubusercontent.com/assets/16782684/12427207/32b5fb42-bede-11e5-925a-6b34ef5ed0de.JPG)
The left one schould be total red and the right one total green.

**Comment by ExileFox** [comment]
I don't think this application supports multiple devices

**Comment by ExileFox** [comment]
@ByteBitter do you get a warning message like  "does not seem to be a launchpad"

**Comment by ByteBitter** [comment]
I don´t get the warning message.
